<?php
namespace Mittwald\ApiToolsPHP\Generator;

class CommentUtils
{
    const AutoGeneratorURL = "https://github.com/mittwald/api-client-php-builder";
    const AutoGenerationNotice = <<<EOT
DO NOT EDIT; this class was generated by the mittwald/api-client-builder package (https://github.com/mittwald/api-client-php-builder). Please make any changes there.
EOT;

    public static function generateOperationLink(string $tag, string $operationId): string
    {
        $tag = str_replace(" ", "-", $tag);
        $tag = preg_replace('/[^a-zA-Z0-9-]/', '', $tag);

        return "https://developer.mittwald.de/reference/v2/#tag/{$tag}/operation/{$operationId}";
    }

}